{{- if and (not $.Values.DremioAdmin) (($.Values).masterCoordinator).persistentStorage -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dremio-master-pv
spec:
  capacity:
    storage: {{ $.Values.coordinator.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: dremio-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: {{ include "dremio.storageClass.provisioner" $ }}
    # TODO
{{/*    volumeHandle: fs-07153762fda153818*/}}
{{- end -}}