{{- if and ((($.Values).masterCoordinator).automatedBackups) (not $.Values.DremioAdmin) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dremio-automated-backups
spec:
  schedule: "{{ $.Values.masterCoordinator.automatedBackups.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "{{- template "dremio.coordinator.serviceAccountName" $ }}"
          automountServiceAccountToken: true
          containers:
            - name: dremio-automated-backups
              image:  bitnami/kubectl:1.28.4
              imagePullPolicy: IfNotPresent
              command: [
                "kubectl",
                "exec",
                "dremio-master-0",
                "--container",
                "dremio-master-coordinator",
                "--",
                "env",
                "DREMIO_MAX_HEAP_MEMORY_SIZE_MB={{ include "dremio.automatedBackups.heapMemory" $ }}",
                "/opt/dremio/bin/dremio-admin",
                "backup",
                "-l",
                "-d",
                "{{ include "dremio.automatedBackups.distStorage" $ | trim }}",
              ]
          restartPolicy: OnFailure
{{- end -}}