{{- if  (((($.Values).masterCoordinator).automatedBackups)) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dremio-automated-backups
spec:
  schedule: "{{ $.Values.masterCoordinator.automatedBackups.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "{{- template "dremio.coordinator.serviceAccountName" $ }}"
          automountServiceAccountToken: true
          containers:
            - name: dremio-automated-backups
              image:  bitnami/kubectl:1.28.4
              imagePullPolicy: IfNotPresent
              command: [
                "kubectl",
                "exec",
                "dremio-master-0",
                "--container",
                "dremio-master-coordinator",
                "--",
                "/opt/dremio/bin/dremio-admin",
                "backup",
                "-l",
                "-d",
                "{{ include "dremio.backups.distStorage" $ | trim }}",
              ]
              env:
              - name: DREMIO_JAVA_CLIENT_EXTRA_OPTS
                value: "-Xmx4g"
          restartPolicy: OnFailure
{{- end -}}
