---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/quarkus-version: "3.14.2"
    app.quarkus.io/commit-id: "ec8e35efc84b3aa411f6f483165579c633ce1ae2"
    app.quarkus.io/vcs-uri: "https://github.com/dremio/dremio.git"
    app.quarkus.io/build-timestamp: "2024-11-20 - 12:22:01 +0000"
  labels:
    app.kubernetes.io/name: "engine-operator"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "quarkus"
  name: "engine-operator"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "engine-operator"
      app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: "3.14.2"
        app.quarkus.io/commit-id: "ec8e35efc84b3aa411f6f483165579c633ce1ae2"
        app.quarkus.io/vcs-uri: "https://github.com/dremio/dremio.git"
        app.quarkus.io/build-timestamp: "2024-11-20 - 12:22:01 +0000"
      labels:
        app.kubernetes.io/managed-by: "quarkus"
        app.kubernetes.io/name: "engine-operator"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
      namespace: "default"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "QUARKUS_OPERATOR_SDK_CONTROLLERS_REPLICA_NAMESPACES"
          value: {{ .Values.watchNamespaces }}
        - name: "QUARKUS_OPERATOR_SDK_CONTROLLERS_ENGINE_NAMESPACES"
          value: {{ .Values.watchNamespaces }}
        image: "docker.io/elliot.west/engine-operator:{{ .Chart.AppVersion }}"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: "engine-operator"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/started"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: "engine-operator"
