apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dremioengines.dremio.com
spec:
  group: dremio.com
  names:
    kind: DremioEngine
    plural: dremioengines
    singular: dremioengine
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.imageName
          name: IMAGE_NAME
          priority: 3
          type: string
        - jsonPath: .spec.maxReplicas
          name: MAX_REPLICAS
          priority: 2
          type: integer
        - jsonPath: .spec.minReplicas
          name: MIN_REPLICAS
          priority: 2
          type: integer
        - jsonPath: .spec.replicas
          name: REPLICAS
          priority: 1
          type: integer
        - jsonPath: .spec.size
          name: SIZE
          priority: 1
          type: string
        - jsonPath: .status.runningExecutors
          name: RUNNING_EXECUTORS
          priority: 2
          type: integer
        - jsonPath: .status.runningReplicas
          name: RUNNING_REPLICAS
          priority: 2
          type: integer
        - jsonPath: .status.state
          name: STATE
          priority: 1
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                imageName:
                  description: Executor Image name
                  type: string
                maxReplicas:
                  description: TODO
                  maximum: 128.0
                  minimum: 0.0
                  type: integer
                minReplicas:
                  description: TODO
                  maximum: 128.0
                  minimum: 0.0
                  type: integer
                replicas:
                  description: Count of replicas comprising this engine
                  maximum: 128.0
                  minimum: 0.0
                  type: integer
                size:
                  description: "Then engine size, typically a T-shirt style name"
                  enum:
                    - LARGE_V1
                    - MEDIUM_V1
                    - SMALL_V1
                    - XXX_LARGE_V1
                    - XX_LARGE_V1
                    - XX_SMALL_V1
                    - X_LARGE_V1
                    - X_SMALL_V1
                  type: string
              required:
                - imageName
                - maxReplicas
                - minReplicas
                - replicas
                - size
              type: object
            status:
              properties:
                labelSelector:
                  description: Label selector for the Replica scaling
                  type: string
                message:
                  description: TODO
                  type: string
                observedGeneration:
                  type: integer
                reason:
                  description: TODO
                  type: string
                runningExecutors:
                  description: The status of executors that comprise the Engine
                  type: integer
                runningReplicas:
                  description: Count of replicas comprising this engine
                  type: integer
                state:
                  description: dTODO
                  enum:
                    - FAILED
                    - RUNNING
                    - STARTING
                  type: string
              required:
                - message
                - runningReplicas
                - state
              type: object
          type: object
      served: true
      storage: true
      subresources:
        scale:
          labelSelectorPath: .status.labelSelector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.runningReplicas
        status: {}
