{{- if $.Values.executorNodeLifecycleService -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dremio-executor-scaler
spec:
  maxReplicas: {{ $.Values.executorNodeLifecycleService.maxNumExecutors | default 50 }}
  minReplicas: {{ $.Values.executorNodeLifecycleService.minNumExecutors | default 1 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dremio-executor
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.executorNodeLifecycleService.cpuAverageUtilization | default 70 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.executorNodeLifecycleService.memoryAverageUtilization | default 70 }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 90
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
        - type: Pods
          value: 1
          periodSeconds: 600 # (i.e., scale down one pod every 10 min)
      selectPolicy: Max
{{- end -}}